[workspace]
resolver = "2"
members = [
  "datafusion-postgres",
  "datafusion-postgres-cli",
  "arrow-pg",
  "datafusion-pg-catalog",
  "datafusion-pg-functions",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94.0"
authors = ["Ning Sun <n@sunng.info>"]
keywords = ["database", "postgresql", "datafusion"]
repository = "https://github.com/datafusion-contrib/datafusion-postgres/"
documentation = "https://docs.rs/crate/datafusion-postgres/"

[workspace.dependencies]
arrow = "59"
arrow-schema = "59"
bytes = "1.11.1"
chrono = { version = "0.4", features = ["std"] }
datafusion = { version = "55" }
futures = "0.3"
pgwire = { version = "0.41", default-features = false }
postgres-types = "0.2"
rust_decimal = { version = "1.42", features = ["db-postgres"] }
tokio = { version = "1", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
